# -*- coding: utf-8 -*-
"""day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iBfUr15beAodjgGv6We69l_onh4b-8D0
"""

a=int(input("Enter a number a: "))
b=int(input("Enter a number b: "))
if a>b:
  print("a is greater than b")
if a<b:
  print("a is less than b")

x = [2, 8, 1, 4, 6, 3, 7]

print ("Sorted List returned :"),
print (sorted(x))


print ("\nReverse sort :"),
print (sorted(x, reverse = True))


# Dictionary
x = {'q':1, 'w':2, 'e':3, 'r':4, 't':5, 'y':6}
print (sorted(x))

# Set
x = {'q', 'w', 'e', 'r', 't', 'y'}
print (sorted(x))

# Frozen Set
x = frozenset(('q', 'w', 'e', 'r', 't', 'y'))
print (sorted(x))

a=200
b=200
if a>=b:
  print("a is greater than b")
if a<=b:
  print("a is less than b")
if a==b:
  print(a)
  print(b)

"""these 2 codes show the differnce between the loop of if statement and if else statement
if statement show more than 1 output whereas in if else show only 1 output
"""

a=200
b=200
if a>=b:
  print("a is greater than b")
elif a<=b:
  print("a is less than b")
elif a==b:
  print(a)
  print(b)

a=100
if a<100:
  print(a,"less than 100")
  if (50<=a<=100):
    print(a,"is between 50 and 100")
  elif (20<=a<=50):
    print(a,"is between 20 and 50")
  else:
    print(a,"is less than 20")
elif(20<=a<=200):
  print(a, "is between 50 and 200")
else:
  print(a,"greator than 200")

"""loops"""

#for loop --- if you know how many times you need to input data
#while loop === terminate when condition is false

total=0
for i in range(5):
  no=int(input("Enter a number"))
  total+=no
print("Sum of 5 numbers",total)

#while loop
total=0
while total<=100:
  no=int(input("Enter a number"))
  total+=no
print("Sum of 5 numbers",total)

a=1
while a<5:
  print("The number s:",a)
  a+=1
print("program end")

x=2
print("loop starts")
while x<10:
  print(x)
  x+=2
print("program ends")



a=[10,28,89,78]
for i in range(len(a)):
  print(a)
print("Good Day")

a=[10,28,89,78]
for i in a:
  print(i)
print("Good Day")

for i in range(10):
  print(str(i)*i)
print("Good day")

for i in range(10):
  print(i*i)
print("Good day")

a=["ken","ren","den","shen"]
b=["men","ven","nest"]
for i in a:
  print(i)
  for j in b:
    print("   ",j)
    break
    print("   ",j)

"""break statements -- terminates the loop statements and transfers execution
continue statement
pass statement
"""

for i in a:
  pass

def sales():
  price=10
  qty=2
  amt=price*qty
  print(amt)
sales()

def sales(qty,price=90):
  amt=price*qty
  print("Total amount",amt)
sales(12)
sales(6,49)

def sales(qty=10,price=90):
  amt=price*qty
  print(amt)
s1=sales(12)
sls=[]
sls.append(sales(price=50))
sls.append(sales())
sls.append(s1)
print(sls)#we are facing problem in showcasing the result of the list

sales(price=30)

def financials(revenue,expenses):
  #this fuction is to calculate profit and profit ratio
  profit=revenue-expenses
  profit_ratio= profit/revenue
  new_financials=(profit,profit_ratio)
  return new_financials
financials(1000,600)
y=financials(4566,900)
print("Profit: ",y[0])
print("Profit ratio: ",y[1])

def convertto (deg):
  f=(deg*9/5)+32
  return (f)
convertto(40)

list=[]
tuple=()
set={}
dict={"key":"value"}

li=[12,34,65,768,79,"set",True,8.3,[45,67],89]
set={12,34,65,768,79,"set",True,4.3}
tuple=(12,34,65,768,79,"set",True,4.3)
print(li)
print(set)
print(tuple)

print(li[6])
print(tuple[2])

list1=["guava","orange","apple","papaya"]
list2=[45,89,53,42]
d=dict(zip(list1,list2))
print(d)
print(list2+list2)
print(list1*3)
print(57 in list1)

li=[12,34,235,56,78,98,44]
del (li)

li=[12,34,235,56,78,98,44]
li.clear()
print(li)
li=[12,34,235,56,78,98,44]
del li[2]
print(li)
li=[12,34,235,56,45,45,78,98,44,45]
li.remove(45)#if the element mentioned in the remove attribute is not present in list it will show a valueerror
# remove attribute only remove 1st occuring of that specific element
li.append(20)
print(li)
li.extend(list1)
print(li)
list2=[45,89,53,42]
list2.insert(3,59)
print(list2)

list=[]
for i in [45,32,5,7,8]:
  list.append(i*2)
print(list)
x=sorted(list)
print(x)

list1=["guava","orange","apple","papaya"]
x=sorted(list1)
print(x)

"""Sort /Sorted
sort() function will modify the list it is called on.
sorted() function will create a new list containing a sorted version of the list

"""

y=[x**2 for x in [2,13,4,9,12]]
y.sort()
print(y[::-1])
print (y[4:2:-1])
print(y)

colors=["red","yellow","green","orange"]
first_col=colors[2]
colors.reverse()
print(colors)
print(first_col)

nus=[23,56,86,980,46,89,78,0,75,3,24,23]
num_min=min(nus)
num_sum=sum(nus)
print(num_min)
print(num_sum)

#The range() function:
# Printing the numbers 0 to 2000
for num in range(2001):
 print(num)

# Using a comprehension to convert a list of names to upper case
colors = ['Red', 'Blue', 'Green', 'Black', 'White']
upper_cols = [cols.upper() for cols in colors]
print (upper_cols)
# Making a copy of a list
colors = ['Red', 'Blue', 'Green', 'Black', 'White']
copy_of_colors = colors[:]
print (copy_of_colors)

#Slicing a list:
# Getting the first three items
colors = ['Red', 'Blue', 'Green', 'Black', 'White']
first_three = colors [:3]
# Getting the middle three items
middle_three = colors[1:4]
# Getting the last three items
last_three = colors[-3:]

"""**TUPLE**"""



tup1 =(1,2,3,'x','y','m')
tup2 =('x','y','m','N')
print (len(tup1))
print (max(tup2))
print (min(tup2))

tup1 =(1,2,3,'x','y','m')
print (tup1 *2)
print ('x' in tup1)

#Example 2 (Multiply one element)
tup1=(10,20,30)
tup2=tup1 [:2]
print(tup2)
'''tup3=tup1[2:]*3
tup1 = tup2+tup3
print (tup1)'''

#Del Tuple
tup1 =(1,2,3)
tup2 =(4,5,6)
tup3 = tup1+tup2
print (tup3)
del (tup2)
print (tup2)#nameerror

"""tuple doesnot support item deletion thus it will show typeerror"""

tup2 = ([5,6,7],[10,11,12],13,14)
print (tup2)
print (type (tup2))
print (type (tup2[0]))
#tup2 [1] = [10,15,14] – Error
tup2[1][1] = [10,15,14]
print (tup2)

Tup2 = (10,11,12)
#List3 = list (Tup2) – Error
Tup5 = tuple (List3)
print (Tup2)
print (List3)
print (Tup5)

x = 'Good Day'
print (len (x))
print (x [2])
print (x [2:8])
print ('o' in x)

a = 'Python'
b = 'Training'
print ('Welcome to %s %s' % (a,b))

a = 'Python '
print (a * 2)
aa = a [0:10] + 'Training'
print (aa)

a = 'Python'
b = 'Training'
print ('Welcome to %d %s' % (a,b))

a = 'Python '
print (a * 2)
aa = a [0:10] + 'Training'
print (aa)

str1 = 'Good Day'
print (str1.find('D'))

a = {1,2,3,4}
b = {3,4,5,6,8}
c = a|b
print (c)
print (a&b)
print (a-b)