# -*- coding: utf-8 -*-
"""matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vh-9JV_olv2ZEaZJW47KiS9PhCCsxoga

### DATA VISUALIZATION USING MATPLOTLIB
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
x=[4,6,2,8,9]
y=[3,9,5,7,8]
plt.plot(x,y)

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
x=[42,64,32,58,79]
y=[23,19,35,37,85,87,22,12,32,34]
plt.plot(x,y)

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import numpy as np
# %matplotlib inline
x=np.arange(1,9)
y=np.arange(9,17)
plt.plot(x,y)

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
import numpy as np
x=[4,26,2,8,19]
y=[13,9,15,27,8]
plt.plot(y,x,color="green",linestyle="dotted",label="First one",alpha=0.5)
plt.title("Representation of 3 Observations")
x1=np.arange(1,9)
y1=np.arange(17,25)
plt.plot(x1,y1,label="second one")
x2=[4,6,16.9,8,19]
y2=[3,9,11,17,28]
plt.plot(x2,y2,label="third one")
plt.grid()
plt.legend(loc="upper right",shadow=True,fontsize="large")

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
x=[4,6,2,8,9]
y=[3,9,5,7,8]
plt.plot(y,x,color="green",linestyle="dotted")

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
x=[4,6,2,8,9]
y=[3,9,5,7,8]
plt.plot(x,y,color="cyan",linewidth=15)
plt.grid()

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
x=[4,5,0,6,5,2,8,9]
y=[3,7,2,9,5,6,7,8]
plt.plot(y,x,color="red",linestyle="dashdot")
plt.xlabel("day")
plt.ylabel("time utilized")
plt.title("My routine")

import matplotlib.pyplot as plt
import numpy as np
x=np.arange(1,9)
y=[30,56,78,67,75,90,100,89]
plt.xlabel("time ")
plt.ylabel("Speed of car")
plt.title("time taken by car to cover a specific distance")
plt.plot(x,y,color="green",linewidth=9,linestyle="solid",markeredgecolor="black",marker="+",markersize=30)
plt.plot(x,y,"r*-")

x=np.arange(1,9)
y=[30,56,78,67,75,90,100,89]
plt.title("barkha performance")
plt.xlabel("time invested by her")
plt.ylabel("intrest generated by her")
plt.plot(x,y,"g*-.",marker="+", markersize=45)

x=np.arange(1,9)
y=[30,56,78,67,75,90,100,89]
plt.title("barkha performance")
plt.xlabel("time invested by her")
plt.ylabel("intrest generated by her")
plt.plot(x,y,"g+--",alpha=0.75,linewidth=5)

import matplotlib.pyplot as plt
import numpy as np
x=np.arange(1,9)
y=[30,56,78,67,75,90,100,89]
plt.xlabel("time ")
plt.ylabel("Speed of car")
plt.title("time taken by car to cover a specific distance")

plt.plot(x,y,"*")

"""## BAR CHART"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

company=['GOOGL','AMZN','MSFT','FB']
revenue=[90,136,89,27]

"""## HISTOGRAM"""

blood_sugar=[86,89,122,120,111,98,87,140,113, 85, 90, 150, 149, 88, 93, 115, 135, 80, 77, 82, 129]
plt.hist(blood_sugar,rwidth=0.95,bins=[80,100,125,150,180])
plt.xlabel(" blood sugar ")
plt.ylabel("Number of patients")
plt.title("Blood sugar level chart")
blood_sugar_men = [113, 85, 90, 150, 149, 88, 93, 115, 135, 80, 77, 82, 129]
blood_sugar_women = [67, 98, 89, 120, 133, 150, 84, 69, 89, 79, 120, 112, 100]
plt.hist([blood_sugar_men,blood_sugar_women], color=["orange","green"],rwidth=0.95,bins=[80,100,125,150,180])

"""display()
widgets aree represented in the backend by a single object
"""

