# -*- coding: utf-8 -*-
"""workshop_program2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QvaI7zF7Go7odlLS-Ho6NTeF5k-YVBos

dataframe---It is a tabular structure
series--- it is a 1d structure

## intro to panda
"""

import pandas as pd
daa={"day":"1\2\2017"}
df1=pd.DataFrame()
df1

c=open("/content/sample_data/california_housing_test.csv","r")
c.read()

import pandas as pd

mydataset = {
  'longitude': ["-122.050000", "-118.300000", "-117.810000"],
  'latitude': ["37.370000","34.260000","33.780000"]
}
df=pd.DataFrame(mydataset)
df1=pd.read_csv("/content/sample_data/california_housing_test.csv")

print(df1)
print(df)

import pandas as pd
info = {
    'Name': ['Barkha','Supriya','Shreya','Gauri','Parth','Nupur','sahil'],
    'Marks': [32,35,28,24,32,31,36],
    'age': [18,19,19,18,19,17,19],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny',"rainy"]
}
df1 = pd.DataFrame(info)

df1

df1["age"].max()

df1.head(2)

df1["Name"][df1["age"]>=df1["age"].max()]

df1["age"]

df1[df1["Marks"]>=df1["Marks"].max()]

df1[df1["Marks"]>=30]

df1.tail(3)

df1.shape

type(df1.Name)

type(df1["Name"])

import pandas as pd
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}
df1 = pd.DataFrame(weather_data)
df = pd.read_csv("weather_data.csv")
df1

import pandas as pd
df = pd.read_csv("weather_data.csv")
df.head(2)

df.tail(2)

df[2:8]

"""# Operations On DataFrame"""

df["temperature"]==32

df["temperature"].max()

df[df.temperature<=34]

df["day"][df["temperature"]==df["temperature"].max()]

df[df["temperature"]==df["temperature"].max()]

df["temperature"].std()

df.describe()

df.index

df

df.set_index("temperature")

df.set_index("temperature",inplace=True)

df.loc[35]

df.reset_index(inplace=True)
df.head()

df

df1.describe()

df1["Marks"].std()

df1["Name"].max()

df1

df1.set_index("Name",inplace=True)

df1

df1.loc['Supriya']

df1.reset_index(inplace=True)

df1

"""# Different Ways Of Creating Dataframe"""

daf=pd.read_csv("/content/weather_by_cities.csv")
daf

weather_data = [
    ('1/1/2017',32,6,'Rain'),
    ('1/2/2017',35,7,'Sunny'),
    ('1/3/2017',28,2,'Snow')
]
df = pd.DataFrame(data=weather_data, columns=['day','temperature','windspeed','event'])
df

weather_data = [
    {'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
    {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
    {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},

]
df = pd.DataFrame(data=weather_data, columns=['day','temperature','windspeed','event'])
df

"""## Groupby"""

import pandas as pd
df = pd.read_csv("weather_by_cities.csv")
df

"""### For this dataset, get following answers,
What was the maximum temperature in each of these 3 cities?
What was the average windspeed in each of these 3 cities?
"""

g=df.groupby("city")
g

for city,data in g:
  print("city: " ,city)
  print("data: ",data)

g.get_group('paris')

g.max()

g.mean()

g1=df1.groupby("Name")
g1

for Marks,event in g1:
  print("MArks:",Marks)
  print("event: ",event)

g1.get_group("Supriya")

g1.min()

g1.describe()

g1.size()

g1.count()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
g.plot()

p1=pd.read_csv("/content/weather_data.csv")
p1

g3=p1.groupby("temperature")
g3

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
g3.plot()

"""## CONCATENATION"""

us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

import pandas as pd

india_weather = pd.DataFrame({
    "city": ["mumbai","delhi","banglore"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
india_weather

df = pd.concat([india_weather, us_weather], keys=["india", "us"])
df

df = pd.concat([india_weather, us_weather], ignore_index=True)
df

df = pd.concat([india_weather, us_weather], ignore_index=False)
df

temperature_df = pd.DataFrame({
    "city": ["mumbai","delhi","banglore"],
    "temperature": [32,45,30],
}, index=[0,1,2])
temperature_df

windspeed_df = pd.DataFrame({
    "city": ["delhi","mumbai"],
    "windspeed": [7,12],
}, index=[1,0])
windspeed_df

a=pd.concat([temperature_df,windspeed_df],axis=0)
a

a=pd.concat([temperature_df,windspeed_df],axis=1)
a

s=pd.Series([23,27,18,28],name="event")
s

d=pd.concat([temperature_df,s],axis=1)
d

